[project]
name = "mobile-project-jira-tickets-management"
version = "0.1.0"
description = "Scripts for mobile project jira tickets management"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.3.3",
]

[dependency-groups]
dev = [
    "ruff>=0.14.2",
]
